// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_danger': string;
  'root_info': string;
  'root_primary': string;
  'root_secondary': string;
  'root_success': string;
  'root_warning': string;
}
export const cssExports: CssExports;
export default cssExports;
