// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'dot': string;
  'page': string;
  'page_active': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
