// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'endAdornment': string;
  'input': string;
  'root': string;
  'root_large': string;
  'startAdornment': string;
}
export const cssExports: CssExports;
export default cssExports;
