// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_green': string;
  'root_large': string;
  'root_primary': string;
  'root_small': string;
}
export const cssExports: CssExports;
export default cssExports;
