// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_P14': string;
  'root_P16': string;
  'root_P18': string;
  'root_P20': string;
  'root_P24': string;
  'root_P9': string;
}
export const cssExports: CssExports;
export default cssExports;
