// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'background': string;
  'columnItems': string;
  'redSquare': string;
  'rowItems': string;
}
export const cssExports: CssExports;
export default cssExports;
