// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'container': string;
  'container_hasImage': string;
  'controlButton': string;
  'controls': string;
  'input': string;
  'modal': string;
  'modalContent': string;
  'modalSaveButton': string;
  'root': string;
  'urlButton': string;
}
export const cssExports: CssExports;
export default cssExports;
