// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'caret': string;
  'count': string;
  'menu': string;
  'option': string;
  'root': string;
  'select': string;
  'select_menuOpen': string;
}
export const cssExports: CssExports;
export default cssExports;
