// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'root': string;
  'root_H1': string;
  'root_H1Plus': string;
}
export const cssExports: CssExports;
export default cssExports;
