// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closeButton': string;
  'modal': string;
  'root': string;
  'root_visible': string;
}
export const cssExports: CssExports;
export default cssExports;
