// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkbox': string;
  'checkbox_checked': string;
  'checkbox_disabled': string;
  'input': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
